type(0, value).
type(1, value).
type(2, fact).
type(3, value).
type(4, value).
type(5, fact).
type(6, value).
type(7, value).
type(8, value).
type(9, value).
type(10, fact).
type(11, fact).
type(12, value).
type(13, policy).
type(14, policy).
evidence(_, _) :- fail.
reason(7, 6).
reason(10, 9).
reason(11, 9).
reason(12, 9).
