type(0, value).
type(1, fact).
type(2, value).
type(3, fact).
type(4, fact).
type(5, fact).
type(6, fact).
type(7, testimony).
type(8, value).
type(9, fact).
type(10, fact).
type(11, value).
type(12, value).
type(13, policy).
type(14, policy).
type(15, policy).
type(16, value).
type(17, fact).
type(18, fact).
type(19, fact).
evidence(_, _) :- fail.
reason(3, 2).
reason(4, 5).
reason(9, 10).
reason(16, 15).
