type(0, policy).
type(1, value).
type(2, fact).
type(3, value).
type(4, fact).
type(5, value).
type(6, policy).
type(7, value).
type(8, value).
type(9, value).
type(10, value).
type(11, value).
type(12, value).
type(13, value).
type(14, value).
type(15, value).
evidence(_, _) :- fail.
reason(4, 3).
reason(8, 7).
reason(9, 7).
reason(11, 10).
