type(0, policy).
type(1, fact).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, testimony).
type(6, testimony).
type(7, policy).
type(8, value).
type(9, value).
type(10, testimony).
type(11, testimony).
reason(2, 1).
reason(3, 1).
reason(4, 1).
reason(5, 1).
reason(6, 1).
reason(1, 0).
