type(0, testimony).
type(1, testimony).
type(2, value).
type(3, fact).
type(4, value).
type(5, policy).
type(6, fact).
type(7, fact).
type(8, testimony).
type(9, testimony).
type(10, fact).
type(11, testimony).
type(12, testimony).
type(13, fact).
type(14, value).
type(15, value).
type(16, fact).
type(17, value).
type(18, testimony).
type(19, testimony).
type(20, value).
type(21, value).
type(22, value).
evidence(_, _) :- fail.
reason(3, 4).
reason(20, 21).
