type(0, value).
type(1, value).
type(2, value).
type(3, fact).
type(4, fact).
type(5, policy).
type(6, policy).
type(7, value).
type(8, value).
type(9, fact).
type(10, value).
type(11, value).
type(12, policy).
type(13, value).
type(14, policy).
type(15, policy).
evidence(_, _) :- fail.
reason(3, 2).
reason(7, 6).
reason(11, 12).
reason(13, 12).
