type(0, policy).
type(1, policy).
type(2, testimony).
type(3, value).
type(4, testimony).
type(5, testimony).
type(6, testimony).
type(7, testimony).
evidence(_, _) :- fail.
reason(2, 0).
reason(3, 0).
reason(4, 0).
reason(5, 0).
reason(6, 0).
reason(7, 0).
reason(0, 1).
reason(2, 1).
reason(3, 1).
reason(4, 1).
reason(5, 1).
reason(6, 1).
reason(7, 1).
