type(0, testimony).
type(1, testimony).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, testimony).
type(6, testimony).
type(7, testimony).
type(8, testimony).
type(9, value).
type(10, testimony).
type(11, testimony).
type(12, testimony).
type(13, value).
type(14, testimony).
type(15, value).
type(16, testimony).
type(17, value).
type(18, value).
type(19, testimony).
type(20, value).
type(21, value).
evidence(_, _) :- fail.
reason(2, 1).
reason(5, 4).
reason(8, 7).
reason(11, 10).
reason(19, 18).
