type(0, testimony).
type(1, testimony).
type(2, policy).
type(3, value).
type(4, value).
type(5, testimony).
type(6, value).
type(7, value).
type(8, value).
type(9, fact).
type(10, value).
type(11, value).
type(12, value).
evidence(_, _) :- fail.
reason(3, 2).
reason(4, 3).
reason(11, 8).
reason(9, 8).
reason(10, 8).
