type(0, value).
type(1, fact).
type(2, fact).
type(3, value).
type(4, fact).
type(5, value).
type(6, value).
type(7, value).
type(8, policy).
type(9, policy).
type(10, value).
type(11, value).
type(12, testimony).
type(13, testimony).
type(14, value).
type(15, policy).
type(16, value).
type(17, fact).
type(18, policy).
evidence(_, _) :- fail.
reason(5, 4).
reason(7, 6).
reason(11, 10).
reason(17, 16).
