type(0, policy).
type(1, fact).
type(2, value).
type(3, value).
type(4, value).
type(5, value).
type(6, value).
type(7, value).
type(8, value).
type(9, value).
evidence(_, _) :- fail.
reason(1, 0).
reason(6, 0).
reason(3, 2).
reason(4, 2).
reason(5, 4).
reason(7, 6).
reason(8, 7).
reason(9, 7).
