type(0, value).
type(1, value).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, value).
type(6, value).
type(7, value).
type(8, value).
type(9, policy).
type(10, policy).
type(11, value).
type(12, value).
type(13, value).
type(14, policy).
evidence(_, _) :- fail.
reason(2, 1).
reason(6, 7).
reason(11, 10).
reason(13, 14).
