type(0, testimony).
type(1, testimony).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, policy).
type(6, value).
type(7, policy).
type(8, testimony).
type(9, value).
type(10, testimony).
type(11, testimony).
type(12, value).
evidence(_, _) :- fail.
reason(0, 5).
reason(1, 5).
reason(2, 5).
reason(3, 5).
reason(6, 5).
reason(9, 7).
reason(8, 9).
