type(0, testimony).
type(1, fact).
type(2, fact).
type(3, fact).
type(4, reference).
type(5, testimony).
type(6, fact).
type(7, value).
type(8, fact).
type(9, fact).
type(10, value).
type(11, value).
type(12, policy).
reason(4, 3).
reason(11, 12).
