type(0, policy).
type(1, testimony).
type(2, fact).
type(3, policy).
type(4, testimony).
type(5, testimony).
type(6, testimony).
type(7, testimony).
type(8, testimony).
type(9, testimony).
type(10, testimony).
type(11, testimony).
type(12, value).
type(13, value).
type(14, value).
type(15, value).
type(16, value).
evidence(_, _) :- fail.
reason(13, 12).
