type(0, value).
type(1, value).
type(2, fact).
type(3, fact).
type(4, value).
type(5, value).
type(6, fact).
type(7, value).
type(8, policy).
type(9, policy).
type(10, value).
type(11, value).
type(12, value).
type(13, value).
type(14, value).
type(15, fact).
type(16, value).
type(17, value).
evidence(_, _) :- fail.
reason(11, 9).
reason(12, 9).
reason(17, 16).
