type(0, fact).
type(1, value).
type(2, testimony).
type(3, policy).
type(4, value).
type(5, policy).
type(6, policy).
type(7, policy).
type(8, policy).
type(9, policy).
type(10, policy).
type(11, fact).
type(12, value).
type(13, value).
type(14, fact).
type(15, value).
evidence(_, _) :- fail.
reason(1, 0).
reason(4, 3).
reason(5, 3).
reason(15, 14).
