type(0, value).
type(1, fact).
type(2, fact).
type(3, fact).
type(4, value).
type(5, value).
type(6, fact).
type(7, fact).
type(8, value).
type(9, value).
type(10, policy).
type(11, policy).
type(12, policy).
type(13, value).
type(14, value).
type(15, value).
type(16, value).
type(17, value).
type(18, value).
evidence(_, _) :- fail.
reason(13, 12).
reason(14, 12).
