type(0, value).
type(1, testimony).
type(2, value).
type(3, testimony).
type(4, testimony).
type(5, testimony).
type(6, value).
type(7, testimony).
type(8, testimony).
type(9, testimony).
type(10, testimony).
type(11, testimony).
type(12, testimony).
type(13, testimony).
type(14, testimony).
type(15, value).
type(16, testimony).
type(17, testimony).
type(18, testimony).
type(19, testimony).
type(20, testimony).
type(21, testimony).
type(22, policy).
evidence(_, _) :- fail.
reason(16, 17).
