type(0, testimony).
type(1, value).
type(2, value).
type(3, value).
type(4, fact).
type(5, value).
type(6, fact).
type(7, fact).
type(8, value).
type(9, testimony).
type(10, value).
type(11, testimony).
type(12, value).
type(13, value).
evidence(_, _) :- fail.
reason(2, 1).
reason(4, 3).
reason(8, 3).
reason(4, 5).
reason(10, 9).
reason(9, 11).
reason(9, 13).
