type(0, testimony).
type(1, testimony).
type(2, policy).
type(3, fact).
type(4, fact).
type(5, value).
type(6, fact).
type(7, fact).
type(8, fact).
type(9, fact).
type(10, testimony).
type(11, testimony).
type(12, fact).
type(13, testimony).
type(14, fact).
type(15, testimony).
type(16, testimony).
type(17, value).
type(18, testimony).
type(19, testimony).
type(20, value).
type(21, fact).
type(22, value).
evidence(_, _) :- fail.
reason(6, 5).
reason(9, 8).
reason(16, 17).
