type(0, testimony).
type(1, testimony).
type(2, testimony).
type(3, testimony).
type(4, value).
type(5, value).
type(6, testimony).
type(7, testimony).
type(8, value).
type(9, testimony).
type(10, testimony).
type(11, testimony).
type(12, value).
type(13, testimony).
type(14, fact).
type(15, reference).
reason(14, 13).
reason(15, 13).
reason(4, 5).
reason(6, 7).
reason(11, 10).
