type(0, value).
type(1, testimony).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, testimony).
type(6, value).
type(7, value).
type(8, testimony).
type(9, testimony).
type(10, testimony).
type(11, value).
type(12, value).
type(13, value).
type(14, testimony).
type(15, testimony).
type(16, testimony).
type(17, testimony).
type(18, testimony).
type(19, testimony).
type(20, testimony).
type(21, testimony).
type(22, testimony).
type(23, value).
type(24, policy).
evidence(_, _) :- fail.
reason(12, 13).
reason(19, 21).
reason(20, 21).
reason(23, 24).
