type(0, value).
type(1, testimony).
type(2, testimony).
type(3, value).
type(4, value).
type(5, fact).
type(6, value).
type(7, fact).
type(8, value).
type(9, fact).
type(10, value).
type(11, value).
type(12, policy).
type(13, policy).
evidence(_, _) :- fail.
reason(1, 0).
reason(2, 0).
reason(3, 0).
reason(10, 9).
reason(11, 9).
reason(9, 12).
