type(0, policy).
type(1, testimony).
type(2, testimony).
type(3, testimony).
type(4, testimony).
type(5, testimony).
type(6, testimony).
type(7, testimony).
type(8, fact).
type(9, value).
type(10, value).
type(11, fact).
type(12, testimony).
type(13, value).
type(14, value).
type(15, value).
type(16, testimony).
type(17, value).
type(18, value).
type(19, policy).
type(20, value).
evidence(_, _) :- fail.
reason(18, 19).
reason(20, 19).
