type(0, value).
type(1, value).
type(2, fact).
type(3, fact).
type(4, fact).
type(5, value).
type(6, testimony).
type(7, reference).
type(8, testimony).
type(9, policy).
type(10, value).
type(11, testimony).
type(12, fact).
type(13, testimony).
type(14, value).
type(15, testimony).
type(16, value).
type(17, reference).
type(18, reference).
type(19, reference).
type(20, reference).
type(21, reference).
type(22, value).
type(23, value).
reason(7, 6).
reason(_, _) :- fail.
